### ISSUE TITLE
Flow control for creating new streams

### ISSUE THREAD

**Issue by vasilvv** [w3c/webrtc-quic#112]
In general, I like the read/write API for QUIC stream data (though I think there should be a better story for controlling send buffer size, etc).  In IETF QUIC, opening new streams is flow controlled in the same way sending data on an individual stream is, but the behavior of API seems to be different: it seems to imply the streams are created immediately when the connection is fully open.  There is a similar discrepancy in terms of reading: the client can choose when to read data from streams, but has to be event-notified about when a new stream is received.  I suggest making receiving incoming streams pull-based (i.e. you call receiveStream() and get a promise that's fulfilled when a new stream is received).

**Comment by pthatcherg** [comment]
Perhaps we should break this up into 2 issues:

1.  The send side: we need to add some text to specify that we delay resolving the promise under situations of stream creation flow control.

2.  The receive side: we would need to change the API to allow the JS to not keep up with incoming streams, much like we do with receiving datagrams and reading bytes from a stream.  receiveStream() is one option (which is like readInto() and receiveDatagrams()).  Another option is to have WHATWG streams (a stream of streams).

**Comment by pthatcherg** [comment]
I'll take a shot at the receive side.  Seth said he'd take a shot at the send side.

**Comment by shampson** [comment]
I was reading section [4.5](https://tools.ietf.org/html/draft-ietf-quic-transport-19#section-4.5) regarding the stream flow control.

@vasilvv - Are you implying sending a MAX_STEAM frame, to indicate that more streams can be opened based upon the pull based API? From the spec:

> As with stream and connection flow control, this document leaves when
   and how many streams to advertise to a peer via MAX_STREAMS to
   implementations.  Implementations might choose to increase limits as
   streams close to keep the number of streams available to peers
   roughly consistent.

**Comment by shampson** [comment]
Reopening this for receive side still, which wasn't addressed in the PR

**Comment by aboba** [comment]
Moved to the WebTransport repo: https://github.com/WICG/web-transport/issues/98
