### ISSUE TITLE
RTCTransport.stop() error code not exposed to remote side

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#119]
This was an issue left off from the PR that introduced the QuicTransportStopInfo in stop(). Currently the API doesn't expose the info on the remote side - only the onstatechange event fires. I think there's a few options for a fix here.

1. (my preferred) Change RTCQuicTransport onstatechange event to two promises (connected & closed). I addressed this in [issue 83](https://github.com/w3c/webrtc-quic/issues/83).
2. Add another event or promise specific to the remote side calling stop(). This means an additional event/promise firing for the state change. API:
```idl
attribute Promise<RTCQuicTransportStopInfo> remoteStopped;
// or
attribute EventHandler onRemoteStopped;
```
3. Add RTCQuicTransportStopInfo state change event.

Curious to hear thoughts proposing #2 over #1 and why.

**Comment by shampson** [comment]
As discussed - we can just do #3 here to keep the onstatechange event.

**Comment by aboba** [comment]
@shampson Closing, since I believe that this issue is now addressed in the WebTransport specification.  If not, please open an Issue in the [WebTransport repo](https://github.com/WICG/web-transport/issues).
