### ISSUE TITLE
Alternatively using stats for dropped datagrams

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#124]
Currently the datagram API adds null values to the sequence of datagrams given in the returned promise from receivedDatagrams():

> If too many datagrams are queued between calls to receiveDatagrams(), the implementation may drop datagrams and replace them with a null value in the sequence of datagrams returned in the next call to receiveDatagrams(). One null value may represent many dropped datagrams.

Alternatively we could just add a stat for number of datagrams dropped on the receive side.

Pros
- More intuitive API, by not giving a null value in your returned sequence
- Still gives the necessary information so you can relay to the send side to slow down

Cons
- Less granularity (is this necessary??)
- Doesn't force the developer to think of the case for datagrams being dropped

**Comment by shampson** [comment]
As discussed, stats sounds good here instead of null values. Will add a PR.

**Comment by aboba** [comment]
Moved to the WebTransport repo as https://github.com/WICG/web-transport/issues/97
