### ISSUE TITLE
Is RTCQuicTransport dead?

### ISSUE THREAD

**Issue by john-livelyvideo** [w3c/webrtc-quic#136]

**Comment by dontcallmedom** [comment]
dead may be a strong word (although it's clearly inactive at the moment); the focus has moved from P2P scenarios to client-server under the WebTransport realm https://github.com/w3c/webtransport

**Comment by john-livelyvideo** [comment]
Thanks @dontcallmedom, appreciate it!  One last question, with respect to TURN servers, is it possible to use webtransport instead of TCP?

**Comment by alvestrand** [comment]
No, there is no specification for TURN servers using webtransport.
