### ISSUE TITLE
Purpose of targetWriteBufferedAmount

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#16]
It's unclear to me what the purpose of the targetWriteBufferedAmount is. When calling waitForWriteable, it creates a smaller threshold for the amount you want to write. This means that the write buffer needs to free more space before writing, then with the larger threshold by using the default [[MaxWriteBufferedAmount]]. Setting it allows you to make sure the write buffer doesn't exceed this "target" amount written to it.

What's unclear to me is why you would want to set this every time you call waitForWriteable. Why not do something similar like setTargetReadBufferedAmount (setTargetWriteBufferedAmount), and pull this out of the waitForWriteable?

**Comment by aboba** [comment]
Also, probably should be clear that targets cannot be < 0 (RangeError).
