### ISSUE TITLE
QuicTransport for client-to-server

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#26]
If you want to use a QuicTransport for client-to-server with the current API, you have to do two things that don't necessarily make sense:
 - **Security:** Verify self signed certificates on both sides using remote fingerprints, instead of just verifying the server's certificate with a CA as the QUIC handshake currently supports.
 - **ICE:** With a client-to-server case you don't necessarily need ICE, but this is required with the API by using an IceTransport. There are probably two solutions here:
   - Server terminates ICE (could be ICE lite, which wouldn't be difficult)
   - Don't require an IceTransport. Could support supplying a UDPTransport or Address/Port? 

Thoughts? Problems? Concerns? Since client-to-server seems to be some of the main use cases for this API (file sharing, games, etc.), it seems like this is worth bringing up.

**Comment by aboba** [comment]
@shampson @alvestrand

What is the overall W3C philosophy for API support of QUIC in client-server scenarios? 

Existing W3C APIs that utilize HTTP for client-server communications can utilize QUIC "under the covers" (e.g. QUIC used automatically as a reliable transport whenever HTTP chooses to use it instead of TCP).  When using those existing APIs, certificate verification and use without ICE can be supported. 

However, for communications between a browser and a WebRTC gateway, WebRTC-QUIC might be a better choice.  For that scenario, requiring gateway support for ICE lite seems reasonable.  Note that the way ORTC DLTS/QUIC role determination works, a gateway with an ICE role of "controlled" would imply a  DTLS role of "client", with the browser having an ICE role of "controlling" implying a DTLS role of "server".  This can be a bit awkward for full validation of the gateway certificate.

**Comment by shampson** [comment]
After our last discussion, we envisioned a separate RTCQuicTransport interface for the server/client case. The client side could just supply a url, and there wouldn't be methods for certificates, parameters, etc.

Is the expectation that we would use ICE still? The server could terminate ICE LITE, and the client's RTCQuicTransport would still supply a RTCIceTransport in the constructor. Then we would be using ICE for the consent to communicate still. From the discussion in the TAG review, it seems that there would be some IETF spec work for QUIC before the this authentication can be done at the QUIC level.

**Comment by pthatcherg** [comment]
ICE doesn't provide a lot of value in a client-server model and not requiring it would make the life of a server implementation easier.  So I think we should start with a model where there is no ICE for client-server and then maybe consider adding it later if we feel it's necessary.

I don't understand the issue with consent.  QUIC won't send (many) packets unless the remote side responds to them.  It's just like a websocket or XHR request with TCP: there's no special consent mechanism there as far as I know.  Consent is more and issue with something like RTP that my just keep sending packets even with no response from the remote side.  But perhaps I'm missing something.

**Comment by alvestrand** [comment]
Is this issue talking about client-to-server or peer-to-peer?
ICE is usually a peer-to-peer issue, and two-way mutual authentication is an issue where the responder has to be able to authenticate the initiator.

**Comment by aboba** [comment]
Presumably an `RTCQuicCSTransport` would be for client-server only. 

With respect to the need for consent in a client-server scenario, I’d like to understand the threat model better.  For RTP, the concern was a “voice hammer” attack (e.g. significant bandwidth) from an implementation not supporting circuit-breakers. Is there an equivalent threat in QUIC and if so, can’t this already be executed using XMLHttpRequest?

**Comment by jianjunz** [comment]
IMHO, QuicTransport for client-to-server mode is more like the WebSocket API which provides two-way communication between client and server. It's not limited to be used by WebRTC APIs.

I'm also trying to remove ICE in C/S mode. It might be possible in WebRTC NV as we're adding low level data access APIs. Then we are able to get encoded data and send it to server with any transport API between client and server (HTTP, WebSocket or C/S QUIC).

**Comment by pthatcherg** [comment]
Responding to Harald and jianjunz: lots of people are asking for either client-server use cases or an improved web socket that works over QUIC (depending on the way they think about it, but it amounts to the same things).  We can provide that by basically just adding a constructor that takes a URL.  Then we have one API that works well for all these cases.  So I think we should.

Responding to Bernard, I think we should just never go to connected and let the JS decided what it wants to do.  If it wants to fallback to a websocket or ICE or something else, it can.  If someone wants a higher-level API to handle that, one can make a small JS library to do that.

**Comment by jianjunz** [comment]
Such a constructor will allow us to remove ICE with WebRTC 1.0 APIs. Not sure if this topic (and #67)  is covered at the QUIC session of TPAC.

**Comment by pthatcherg** [comment]
I made a PR for this: https://github.com/w3c/webrtc-quic/pull/73

**Comment by aboba** [comment]
The client-server API is available for inspection here:
https://w3c.github.io/webrtc-quic/cs.html
