### ISSUE TITLE
Listening to QUIC packets before start

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#29]
I have a couple questions regarding listening to QUIC packets before calling start. From the spec:
_"A newly constructed RTCQuicTransport MUST listen and respond to incoming QUIC packets before start() is called."_

The definition for start states that only a single QUIC transport can be multiplexed over one ICE transport. If two QUIC transports are created with the same ICE transport, you cannot call start() on both, unless one QUIC transport first calls stop().

1. What about two QUIC transports created with the same ICE transport without calling start() on either. Would we want **both** QUIC transports to listen/respond to QUIC packets from the same ICE Transport in this case?
2. Why are we responding to QUIC packets before start is called? I can see the case for listening and buffering QUIC packets before calling start(), because you need the remote fingerprints for the handshake. But I'm confused why you need to respond to QUIC packets before calling start.

**Comment by aboba** [comment]
With DTLS, the limitation of a single transport per ICE transport was inherent.  This spec is reusing the DTLS text, but the QUIC protocol has the connection Id, so I believe that the restriction is not necessary for QUIC.  I think the logic for imposing the restriction anyway was that a single RTCQuicTransport can create multiple RTCQuicStream objects so the application would not necessarily require multiple RTCQuicTransport objects.

To answer your questions: 

1. I don't think you'd want multiple QUIC transports to attempt to respond to the same incoming QUIC packets. 

2. start supplies the remote fingerprint info that enables verification.  So before that information is provided (in an Answer), QUIC packets can arrive and negotiation can begin, but it cannot finish prior to verification.
