### ISSUE TITLE
FIN bit receiving on a STREAM isn't clear enough

### ISSUE THREAD

**Issue by robin-raymond** [w3c/webrtc-quic#30]
It's not enough to receive the FIN bit into the implementation's stream. Receiving the FIN bit in this spec must mean both receiving the FIN bit on the wire AND the JS layer needs to have read out all available data. For example, readable slot goes false when FIN bit is received an JS has read out all available data.

**Comment by aboba** [comment]
@robin-raymond Can we define the term "read and finish" to mean "all available data up to the segment with the FIN bit set has been read by the application."
