### ISSUE TITLE
Multiple RTCCertificate fingerprints reflected in RTCQuicParameters.fingerprints

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-quic#33]
According to the WebRTC-PC specification an RTCCertificate can have multiple fingerprints: https://w3c.github.io/webrtc-pc/#dom-rtccertificate-getfingerprints

The description of RTCQuicParameters.fingerprints says:

> Sequence of fingerprints, one fingerprint for each certificate.

Is there any guidance on which fingerprint should be selected if an RTCCertificate has multiple?

**Comment by aboba** [comment]
In WebRTC 1.0 it is mandatory to include the fingerprint computed with the digest algorithm used in the certificate signature. So it would make sense to include the digest algorithm fingerprint for each certificate.
