### ISSUE TITLE
More details for stop()

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-quic#37]
Right now the algorithm for RTCQuicTransport.stop() is:

> Stops and closes the RTCQuicTransport object. Calling stop() when state is closed has no effect.

I think this needs more details. Some questions we thought about:

1. What state do the streams transition to?
2. Are the streams still readable? Writable?
3. Does anything happen to the stream's buffered data?

The same questions may also apply when the remote side calls stop(), which is reflected by an statechange event.

**Comment by aboba** [comment]
Agree that more details are needed.  Should all streams act as though reset() was called?

**Comment by shampson** [comment]
I talked a bit offline about this with Steve. We probably should decide if we want to mirror the streams by having both a "finish" and a "reset" at the RTCQuicTransport level. I think this depends on what the use case is for closing the RTCQuicTransport. What's the main reason to close it, as opposed to finish/reset for streams? Is it for reusing an RTCIceTransport?

If we were to mirror it...
A finish could look like
- Local side will no longer create streams & [[Writeable]] transitions to false (on remote streams can still be created)
- The remote side can still create streams and send data until it receives the finish message at which point [[Readable]] & [[Writeable]] transition to false for all streams
- Once local side receives the finish message it [[Readable]] transitions to false

A reset could look like:
- local side's [[Readable]] & [[Writeable]] transition to false for all streams & it can no longer create streams (on remote streams will be ignored)
- On receiving the close message, the remote side will:
  -  [[Readable]] & [[Writeable]] transition to false for all streams
  - No longer create streams

**Comment by aboba** [comment]
My take is that RTCQuicTransport.stop() results in the actions you have listed under reset.

**Comment by shampson** [comment]
Yes, I think this is equivalent to an "Immediate Close" ([6.13.3](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.6.13.3)): "_Any closing frame causes all streams to immediately become closed; open streams can be assumed to be implicitly reset._"

I created a pull request for this.

**Comment by shampson** [comment]
Related to this - Do we also want to set the stream's [[Readable]] & [[Writable]] states to false and set the [[QuicStreamState]] to closed when the RTCQuicTransport state transitions to failed? This makes sense to me, you can no longer do anything with your streams. 

I could make a follow up PR for this.
