### ISSUE TITLE
RTCQuicTransport constructed with no certificates

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-quic#41]
What is supposed to happen if an RTCQuicTransport is constructed with no certificates? Should one be generated like in RTCPeerConnection?

**Comment by aboba** [comment]
In Edge when the DtlsTransport was constructed without certificates, we would automatically create them. Assuming that the default certificate is ECDSA, this should not block the UI thread (at least on a PC or tablet).  The reason why certificates are mandatory is to prevent potential issues in an IOT or low end mobile device where the certificate creation might take too long.  We considered making getLocalParameters async to deal with that possibility but it made the examples cumbersome and it seemed easier to require certificate(s) as a constructor argument.

**Comment by aboba** [comment]
Resolution is to make certificates optional in the constructor, in which case an ECDSA certificate will be constructed by default.
