### ISSUE TITLE
RTCQuicTransport: multiple events fire with QUIC error 

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#42]
If a RTCQuicTransport receives a QUIC error both onerror will fire &  onstatechange (failed). Do we want to have two events fire for one thing happening? If so, we should probably specify the order.

**Comment by aboba** [comment]
A few thoughts:

a. The error text should probably be updated to utilize WebRTC 1.0's RTCError framework with error type additions as needed.

b. I believe that both an error event and statechange event can fire on the DtlsTransport in both WebRTC and ORTC,  So we might look at what happens there.

**Comment by shampson** [comment]
It looks like in both WebRTC & ORTC it isn't specified if the two events are fired in a particular order or if just one will fire (it looks like both onerror and onstatechange _would_ fire).

I guess we could either:
- Fire both to be consistent with WebRTC/ORTC
- Only fire one event. I would prefer the onerror event, because this event is dedicated specifically for the errors. 

We could also use the RTCError and add it to the [RTCErrorDetailType](https://www.w3.org/TR/webrtc/#dom-rtcerrordetailtype)

**Comment by pthatcherg** [comment]
Firing both sounds like the best to me.  It would be least surprising to me as a developer.  The order is an interesting question.  What would be least surprising to a developer?  I'm guessing the error then the state change.  It's what you'd like to read in an event log, right?  "error; closed", not "closed; error".

**Comment by shampson** [comment]
I think the error then closed would work here. @aboba does this sound fine? I can create a PR.
