### ISSUE TITLE
Boilerplate change

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-quic#48]
Peter St. Andre has noted that the WebRTC-QUIC document has not yet been adopted as a W3C WEBRTC WG work item, and has requested a boilerplate change:
https://lists.w3.org/Archives/Public/public-webrtc/2018Aug/0040.html

**Comment by aboba** [comment]
Response from Dom: 
https://lists.w3.org/Archives/Public/public-webrtc/2018Sep/0041.html

“editors draft.... really cannot be assumed to have any standing...”

**Comment by pthatcherg** [comment]
He also said we could use the "unofficial draft" label.  I kind of like that idea.

**Comment by aboba** [comment]
Boilerplate has been changed.
