### ISSUE TITLE
Restricting createStream() to state = connected

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-quic#50]
As the spec is written today, it's legal to call createStream on an RTCQuicTransport in any state other than 'closed'. I think that restriction should also apply to the 'failed' state (if the failed state is terminal).

Additionally, is it worth supporting createStream in the 'new' and 'connecting' states? I imagine the actual stream frame wouldn't be sent until the transport is 'connected'. A developer will need to wait for the stream to transition to the 'opening' or 'open' states before using it, so having the object early doesn't seem like much of a convenience.

**Comment by lgrahl** [comment]
Personally, I would prefer a `Promise` in these cases.

**Comment by martinthomson** [comment]
Allowing sending on a stream created prior to connection establishment would be unwise, because you don't want to accept data that doesn't have flow control credit.  That suggests that a promise is wise.

**Comment by aboba** [comment]
Currently, `createStream` returns an `RTCQuicStream` in all states but `closed`.  However, `write` will throw unless the [[Writable]] slot is `true`, and `readInto` will throw unless  the [[Readable]] slot is true. So there are circumstances in which an `RTCQuicStream` will be returned, but may not be usable.  I'm not sure we have clarified all the circumstances determining the value of the [[Readable]] and [[Writable]] slots.

**Comment by shampson** [comment]
From @lgrahl  the PR:

> The main advantage is that one doesn't need to wait for a specific state. The application often only wants to know when it can do its thing and this...
> 
```javascript
const stream = await quicTransport.createSendStream();
 // do stuff...
```
> is just easier (and IMO more appealing) than
> 
```javascript
 quicTransport.onstatechange = () => {
   if (quicTransport.state === 'connected') {
     const stream = quicTransport.createSendStream();
     // do stuff...
   }
 };
```
> (Disclaimer: I omitted error handling for both examples. wink )
> 
> To support this argument with another discussion going on in this PR: It's a fire once event (for that specific state), so a Promise is ideal.

**Comment by shampson** [comment]
@aboba I left this issue open after merging [PR 70](https://github.com/w3c/webrtc-quic/pull/70), given that there wasn't complete consensus on whether to use promises for createStream() or wait for the RTCQuicTransport state to be connected.

I'm happy with promises and am fine closing this issue. Does this need further discussion or can we go ahead and close?

**Comment by lgrahl** [comment]
You are stating that you are fine with the `Promise` approach. The thing is that this is not in the spec. :slightly_smiling_face:
