### ISSUE TITLE
Synchronous Events Firing

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#56]
I think we discussed this offline, but as mentioned in [Client API Design Principles 3.3](https://w3ctag.github.io/design-principles/#favor-asynchronous-events), it isn't recommended to fire synchronous events. This would currently be the case for certain state changes for an RTCQuicStream:
- finish() firing onstatechange to closing/closed
- reset() firing onstatechange to closed
- readInto (when reading the FIN bit) firing onstatechange to closing/closed

We probably have two options here:
1. Don't fire synchronously for these specific onstatechange event cases.
2. Remove the stream onstatechange events and only fire asynchronous events that occur. I could see this meaning that we only fire onremotereset. Otherwise the JS developer knows when the stream's [[Readable]] or [[Writable]] slots go to false.  We know when we've read a FIN bit out (readInto() reads less than asked for), and we know when we've called finish(). In this case we could expose the [[Readable]] and [[Writable]] slots in the API.

Thoughts?

**Comment by pthatcherg** [comment]
I think we agreed to not fire the events (option 1).

**Comment by shampson** [comment]
Update: This is fixed for streams (no longer have a stream state), but the RTCQuicTransport still gets a statechange event when calling stop() and transitioning to the "closed" state.
