### ISSUE TITLE
Expose error code and reason for stop() and reset()?

### ISSUE THREAD

**Issue by steveanton** [w3c/webrtc-quic#62]
According the latest IETF QUIC spec, the [APPLICATION_CLOSE](https://tools.ietf.org/html/draft-ietf-quic-transport-14#section-7.5) frame and [RST_STREAM](https://tools.ietf.org/html/draft-ietf-quic-transport-14#section-7.3) both let the application set a [16-bit error code](https://tools.ietf.org/html/draft-ietf-quic-transport-14#section-11.4). Additionally, APPLICATION_CLOSE lets the application set a UTF8-encoded reason message.

Given that this API is intended to provide low-level control of the QUIC connection, should we expose this information to the developer?

If so, it could look like this:

RTCQuicTransport:
```
void stop(unsigned short errorCode = 0, String reason = "");
attribute EventHandler onclose;  // with e.errorCode and e.reason
```

RTCQuicStream:
```
void reset(unsigned short errorCode = 0);
attribute EventHandler onreset;  // with e.errorCode
```

**Comment by aboba** [comment]
`RTCQuicTransport` has an `onerror` EventHandler.  Assuming that we want to extend `RTCError` from WebRTC 1.0, we could add `RTCError.prototype.quicErrorCode` and `RTCError.prototype.quicReason`. 

We could also add an `onerror` EventHandler for `RTCQuicStream`.

**Comment by shampson** [comment]
@aboba What would the onerror EventHandler for the RTCQuicStream cover?

I like Steve's proposal of exposing the the error code/reason for stop()/onclose and the error code for reset()/onreset. 

Maybe extending RTCError from WebRTC 1.0 should be a separate issue?

**Comment by shampson** [comment]
Issue 83 covers the remaining issue. Closing this.
