### ISSUE TITLE
Cleaning up read API

### ISSUE THREAD

**Issue by shampson** [w3c/webrtc-quic#63]
Let's go through a standard use case of sending data then calling finish() after it's all written.

For simplicity let's say on the send side I have 15 bytes to send, and the receive side I call stream.waitForReadable(10). The following would happen:
- Receive side: calls stream.waitForReadable(10)
- Send side: calls write() with 15 bytes of data
- Receive side (first read):
  - Promise is resolved
  - calls readInto() for the 10 bytes
  - calls waitForReadable(10)
- Receive side (second read):
  - Promise is resolved, since FIN bit has been received and [[ReadBufferedAmount]] (5 bytes) is less than amount asked (10 bytes)
  - calls readInto() for the last 5 bytes (expecting 10)
  - calls waitForReadable(10)
 - Receive side (third read):
   - Promise is resolved since FIN bit has been received and [[ReadBufferedAmount]] (0 bytes) is less than amount asked (10 bytes)
   - calls readInto(), which returns a negative number. This indicates [[Readable]] has transitioned to false and we are done reading.

This works, but I think we could be more explicit. What if instead of the promise resolving with undefined it resolved with:
 - amount available for reading
 - a boolean for the FIN received. This would indicate that this is all that's left to be read.

In the example, upon reading the last 5 bytes [[Readable]] would transition to false and further calls to readInto would return an error. No need for returning a negative number.

**Question:** Is there a reason we need to support setting multiple waitForReadable promises for different amounts? If not, we could take this a step further and only have one method for reading. The promise could return the actual data and the boolean for FIN. No need for a readInto method. This is similar to the WHATWG Readable stream (https://streams.spec.whatwg.org/#default-reader-read).

**Comment by pthatcherg** [comment]
Making a cleaner way of returning the fin bit sounds good to me (negative numbers is a bit hacky).  

But getting rid of readInto is difficult because then the web app wouldn't be able to use its own buffer.  And if we pass a buffer into an async read() method, then the web app wouldn't be able to cancel the read if it wants its buffer back (it just has to wait an indefinite amount of time).  Not perhaps insurmountable, but not a simple change either.

**Comment by shampson** [comment]
A cleaner way of returning the fin bit has been added, and the rest will be cleaned up with incorporating WHATWG streams. I'm closing this issue.
