### ISSUE TITLE
Stats, there got to be stats...

### ISSUE THREAD

**Issue by vr000m** [w3c/webrtc-quic#66]
What do we want to measure, what measurements can we expose from the underlying stack.

counters: bytes, messages, streamsOpened (*state), round trip time, losses/timeouts/resets?
or does the application keep track of bytesSent/received?

**Comment by steveanton** [comment]
Here's the stats that gQUIC collects on the connection level: https://codesearch.chromium.org/chromium/src/net/third_party/quic/core/quic_connection_stats.h

**Comment by vr000m** [comment]
@lennart-csio PTAL

**Comment by shampson** [comment]
Update:
The [origin trial](https://developers.google.com/web/updates/2019/01/rtcquictransport-api) a simple stats API at the RTCQuicTransport level:
```javascript
Promise<RTCQuicTransportStats> getStats();
```
The stats ([defined here](https://cs.chromium.org/chromium/src/third_party/blink/renderer/modules/peerconnection/rtc_quic_transport_stats.idl)):
```idl
dictionary RTCQuicTransportStats {
  double timestamp;
  unsigned long long bytesSent;
  unsigned long long packetsSent;
  unsigned long long streamBytesSent;
  unsigned long long streamBytesReceived;
  unsigned long numOutgoingStreamsCreated;
  unsigned long numIncomingStreamsCreated;
  unsigned long long bytesReceived;
  unsigned long long packetsReceived;
  unsigned long long packetsProcessed;
  unsigned long long bytesRetransmitted;
  unsigned long long packetsRetransmitted;
  unsigned long long packetsLost;
  unsigned long long packetsDropped;
  unsigned long long cryptoRetransmitCount;
  unsigned long long minRttUs;
  unsigned long long smoothedRttUs;
  unsigned long long maxPacketSize;
  unsigned long long maxReceivedPacketSize;
  unsigned long long estimatedBandwidthBps;
  unsigned long long packetsReordered;
  unsigned long long blockedFramesReceived;
  unsigned long long blockedFramesSent;
  unsigned long long connectivityProbingPacketsReceived;
};
```

**Comment by aboba** [comment]
This looks like a good starting point.  Where should we add this?

**Comment by aboba** [comment]
Moved to the WebTransport repo: https://github.com/WICG/web-transport/issues/99
