### ISSUE TITLE
Security and client -> server use cases without ICE

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-quic#67]
If we're going to support client -> server use cases without ICE (by providing a URL instead of an RTCIceTransport), what restrictions will there be on the URL to enforce CORS, etc?  Will it be the same as for web sockets?  It seems like it needs to be.  Otherwise, once could sniff around a local network for services that use QUIC (which, in the future, there may be many) by providing a URL with a local IP.

**Comment by aboba** [comment]
The client-server specification is now available for inspection here:
https://w3c.github.io/webrtc-quic/cs.html
