### ISSUE TITLE
Is RTC prefix needed?

### ISSUE THREAD

**Issue by yutakahirano** [w3c/webrtc-quic#72]
Sorry for bike-shedding.

As I understand most of the contents don't rely on WebRTC. Can we get rid of "RTC" prefix from the interfaces (e.g., QuicTransport, QuicStream, etc)? In the future we may introduce a new way to set up a connection without using RTCPeerConnection and let web developers who don't know anything about RTC use this as a generic networking API.

**Comment by pthatcherg** [comment]
I just made a PR that removes the prefix for client-server things and only leaves it for p2p things.

https://github.com/w3c/webrtc-quic/pull/73

**Comment by aboba** [comment]
@yutakahirano As Peter notes, the "RTC" prefix is needed for the P2P API because the constructor depends on the RTCIceTransport object from the WebRTC 1.0 and ORTC specifications.  However, the client-server API does not depend on objects from WebRTC/ORTC, so the "RTC" prefix is unnecessary.

**Comment by yutakahirano** [comment]
Sounds good. Thank you!

**Comment by aboba** [comment]
The client-server specification (with the RTC prefix removed) is now available here:
https://w3c.github.io/webrtc-quic/cs.html
