### ISSUE TITLE
Add support for unreliable streams

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-quic#75]

**Comment by pthatcherg** [comment]
I made a PR for this: https://github.com/w3c/webrtc-quic/pull/74

Note that I went with an attribute on the stream rather than a parameter in a stream constructor.  Why?  Because if the remote side creates a bidirectional stream, how do you specify you want to send back in an unreliable way?  

If we don't care about unreliable bidirectional streams, then we probably would only want parameters for .reliable on the createSendStream.  The attribute does have the downside that it's not clear if you can keep changing it back and forth and what that would mean, so I can see an argument for doing it that way instead.

In the mean time, I typed this up, so take a look :).

**Comment by pthatcherg** [comment]
OK, I also made option B: using a parameters dictionary:

https://github.com/w3c/webrtc-quic/pull/76


Now we can pick between the two.

**Comment by aboba** [comment]
We should probably think carefully about the use cases.  But I can see having a bi-directional stream with both directions unreliable (e.g. sending media and receiving feedback).

**Comment by aboba** [comment]
@pthatcherg Since we merged the PR, can we close this issue?
