### ISSUE TITLE
What should the ALPN value be?

### ISSUE THREAD

**Issue by pthatcherg** [w3c/webrtc-quic#93]
What should our ALPN be? Victor was suggesting to me that it would be more secure for p2p vs. client/server and that it should be different than "hq". Perhaps something like "wq" (web quic) and "wq2q" (web p2p quic).

**Comment by shampson** [comment]
PR: https://github.com/w3c/webrtc-quic/pull/100

**Comment by pthatcherg** [comment]
The PR was merged, so this is done.
