### ISSUE TITLE
URL scheme

### ISSUE THREAD

**Issue by aboba** [w3c/webrtc-quic#96]
What are the constraints on the URL passed in the constructor argument? Is the intent to support existing schemes (e.g. https:// ) or to define a new scheme for quic?  If the latter, do we need to write an IETF draft defining the new URL scheme?

**Comment by pthatcherg** [comment]
I don't think we should support existing schemes.  It's really just a way to provide a host and port.  We could even change it to take two arguments, one for host and one for port.  I was just trying to be like WebSockets, but there's no reason we really need to be.

**Comment by pthatcherg** [comment]
Related question: if we use a URL (not host + port), what's the default port, or do we require and explicit one?

**Comment by pthatcherg** [comment]
We decided to go with host+port in the constructor
